language: node_js

node_js:
  - "6"

sudo: false

install:
  - npm uninstall typescript
  - npm uninstall tslint
  - npm install
  - npm update

cache:
  directories:
    - node_modules

script:
  - npm test
