language: node_js
node_js:
- '6'
sudo: false
install:
- npm install
- npm update
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build

deploy:
  provider: npm
  email: bgourlie@gmail.com
  api_key:
    secure: wzF5S9W7LWglDd+Cy0mUA+g7q2iRsumqFTwbhlawMxwHeHEDWxEzJC15+meTgx8aOOWeehe8E/DtHf4fW/es5OhdTgehl1iwYUaJh9HN8dbOGcxFrmVTPvoXFsiw+m9pWDPZXv6EYrDBLahOT7Qb/d0Z9s2Ymk0MI+C8smtJJCLFAazp1r0SJ5SBQzIH+rRlNLzna0SbrEYQ6fOMwBGz/1OoeJVfrUwg2kh8/u6/5GCuEuzY6pClAETXGJANff3hN88ksM2FQ04a13AY6ZroxhwKieRjgmvXqauJTd8onwFa9wueQa8U/v3mk+3Fr0/Fh2g29LXUR03gtyV2meCCi0s8I1ZRfLABvwYrply4sSa3HPqOUhIQrT+cpM0/HqXXaaZH5+VuQeOwkGbI16cVF2Mx4JVea4zxgnMm6dtO4xzo4qiSzMimBgRrwKVPtuzlgT+UH5aKBsfzP5OxyiTOZJ+ACZOj5pRoQsbNB0fLzJa2lCt+4iY6Yfdu6Ar/lVilz8pXYTKquvpUiv6V48Mov3SvocC+9U8UgiqFqkzmdEXjp3KT1pkvsPoS7nTTWY4NV3BPuy8lqFevEWT6leYdAJwaXQneN8WwzKYq9THxQ8yJdkLlwqvIfzIKyRb5IBSDE8DXIVmAOdw8DcUFKrhJ6iHhy9TAwJrMQaiiy2aQWS0=
  on:
    repo: bgourlie/6502-disasm
